wopss/RED4ext.SDK

include/RED4ext/Addresses.hpp
include/RED4ext/DynArray.hpp
include/RED4ext/GameEngine.hpp
include/RED4ext/HashMap.hpp
include/RED4ext/REDhash.hpp
include/RED4ext/RTTISystem.hpp
include/RED4ext/RTTITypes.hpp
include/RED4ext/Types/CharacterCustomization.hpp
include/RED4ext/Types/SharedMutex-inl.hpp
include/RED4ext/Types/SharedMutex.hpp
include/RED4ext/Types/SimpleTypes-inl.hpp
include/RED4ext/Types/SimpleTypes.hpp
include/RED4ext/Types/TweakDB-inl.hpp
include/RED4ext/Types/TweakDB.hpp
scripts/patterns.py
src/Types/SharedMutex.cpp
src/Types/SimpleTypes.cpp
src/Types/TweakDB.cpp

1. [Removed] HashMapBase was missing a u64 allocator at the end
2. [Fixed] HashMap had an extra u64 at the beginning which should have been at the end
3. Adjusted offsets in classes/structs that used HashMap and HashMapBase
4. Added HashMap::GetAllocator() 
5. Added custom hasher to HashMap<Key, Value, Hasher>. defaults to casting to u32 if possible
Currently missing 2 classes for unk08 and unk10, will do them eventually if they're useful
Experimental design, any changes are welcome :)
```cpp
auto* tdb = TweakDB::Get();
// Read
{
TweakDBID dbid;
dbid.name_hash = 0x68D39470;
dbid.name_length = 52;
auto* unitCount = tdb->GetVal<int32_t>(dbid);
printf("unitsCount: %d\n", *unitCount);
}
// Read - 2
{
TweakDBID dbid;
dbid.name_hash = 0x68D39470;
dbid.name_length = 52;
auto* tweakVal = …
```

TweakDB and some other small things

---

include/RED4ext/Types/TweakDB-inl.hpp
include/RED4ext/Types/TweakDB.hpp

had a typo in TweakDB that set flatDataBuffer's current size as its capacity. kept reallocating everytime CreateFlatValue was called :)

TweakDB typo fix - reallocation bug

---

include/RED4ext/MemoryAllocators.hpp
include/RED4ext/Types/TweakDB-inl.hpp

The game passes a structure containing the pointer, as seen here:
The game eventually crashes without this fix

Fixed IMemoryAllocator::Free

---

include/RED4ext/DynArray.hpp
include/RED4ext/HashMap.hpp
include/RED4ext/RTTITypes.hpp
include/RED4ext/Types/SimpleTypes-inl.hpp
include/RED4ext/Types/SimpleTypes.hpp
include/RED4ext/Types/TweakDB-inl.hpp
include/RED4ext/Types/TweakDB.hpp

added 'reserve/insert/remove/clear' functions to HashMap 
added 'emplace/remove/clear' functions to DynArray
added 'RemoveAt/InsertAt' functions to CArrayBase RTTI
added 'Move' function to IRTTIType
added '[Create/Remove]Record' and '[Add/Remove]Flat' to TweakDB
added != operator to TweakDBID (fixes a bug where it would implicitly cast into u64)
fixed rare race condition in TweakDB::CreateFlatValue by delaying freeing the buffer (buffer can't go over 0xFFFFFF, won't use a lot of memory)
DynArray/HashMap functions were tested and are working
HashMap Insert/Remove were tested with hash-collisioned keys

TweakDB, DynArray and HashMap

---

include/RED4ext/DynArray.hpp
include/RED4ext/HashMap.hpp
include/RED4ext/Map.hpp
include/RED4ext/SortedArray.hpp
include/RED4ext/Types/SharedMutex-inl.hpp
include/RED4ext/Types/SharedMutex.hpp
include/RED4ext/Types/SpinLock-inl.hpp
include/RED4ext/Types/SpinLock.hpp
src/Types/SpinLock.cpp

https://github.com/WopsS/RED4ext.SDK/blob/1e5a843715e8e61ec6b8989d5bbe8ede8b648430/include/RED4ext/SortedArray.hpp#L61-L69
'SortedUniqueArray' had an issue. 'aItem' would be in an "unspecified" state because 'Emplace' has moved it
Fixed by changing it to this:
https://github.com/WopsS/RED4ext.SDK/blob/1737fe23493358e81d74514dc38861e082e8dfb9/include/RED4ext/SortedArray.hpp#L56-L59
https://github.com/WopsS/RED4ext.SDK/blob/1737fe23493358e81d74514dc38861e082e8dfb9/include/RED4ext/SortedArray.hpp#L182-L203

added SpinLock and InsertOrAssign fixes

---

include/RED4ext/Types/SimpleTypes.hpp

We had Variant known in CET for some time... Trying to get rid of local CET definitions of same things.
Dont know if this is correct for you or not, but this should be it for Variant x)

Define Variant structure

---

include/RED4ext/RTTISystem.hpp
include/RED4ext/RTTITypes.hpp

Filled out several of the RTTISystem methods that return lists of specific types.
The Enum and Bitfield variants take a boolean that checks the first bit of their flags byte, which filters whether they are scripted or native. I've tested that it works that way for Enums, but Bitfields are only implemented as native code and the redscript compiler doesn't currently support bitfields, so it's purely conjecture on my part (they are treated identically though).
There are a few differences between `IRTTISystem::GetClasses()` and `IRTTISystem::GetDerivedClasses()`:
- `GetClasses()` will call `CClass::IsA(aIsAClass)` on each class if `aIsAClass` is not null. 
- `GetClasses()` has an optional filter function that is called on each matching class
- `GetDerivedClasses()` will check each class to …

Added some Get methods to RTTISystem

---

include/RED4ext/Addresses.hpp
include/RED4ext/NativeTypes.hpp
include/RED4ext/RTTISystem-inl.hpp
include/RED4ext/RTTISystem.hpp
include/RED4ext/Scripting/Functions.hpp
include/RED4ext/Scripting/Script-inl.hpp
include/RED4ext/Scripting/Script.cpp
include/RED4ext/Scripting/Script.hpp
scripts/patterns.py

Added a hook to the `RTTIRegistrator` constructor to add callback functions that are called before the `final.redscripts` is loaded, allowing for new native methods to be defined in RED4ext and called from Redscript.
`RTTIRegistrator::Add()` can be called immediately after the dll attaches:
```cpp
RED4EXT_C_EXPORT void RED4EXT_CALL RegisterTypes() {}
RED4EXT_C_EXPORT void RED4EXT_CALL PostRegisterTypes() {}
BOOL APIENTRY DllMain(HMODULE aModule, DWORD aReason, LPVOID aReserved)
{
switch (aReason)
{
case DLL_PROCESS_ATTACH:
DisableThreadLibraryCalls(aModule);
RED4ext::RTTIRegistrator::Add(RegisterTypes, PostRegisterTypes);
break;
}
return TRUE;
}
```
Also fleshed out one of the unknown chunks in the `CBaseFunction` class: a `DataBuffer` to the compiled redscript bytecode

Native func support

---

include/RED4ext/Addresses.hpp
include/RED4ext/Callback.hpp
include/RED4ext/Detail/Callback.hpp
include/RED4ext/Detail/Function.hpp
include/RED4ext/Detail/Memory.hpp
include/RED4ext/JobQueue-inl.hpp
include/RED4ext/JobQueue.hpp
include/RED4ext/Memory/Utils.hpp
include/RED4ext/RTTISystem.hpp
include/RED4ext/ResourceLoader.hpp
include/RED4ext/ResourceReference.hpp
scripts/find_patterns.py
scripts/patterns.py
src/JobQueue.cpp

- Added support for callbacks
```cpp
auto loader = RED4ext::ResourceLoader::Get();
auto token = loader->LoadAsync(R"(base\vehicles\sport\v_sport1_herrera_outlaw_basic_01.ent)");
token->OnLoaded([](RED4ext::Handle<RED4ext::CResource>& aResource) {
Log("Resource is loaded");
});
```
```cpp
auto rtti = RED4ext::CRTTISystem::Get();
rtti->AddRegisterCallback([&rtti] {
Log("RTTI Type Registration");
});
```
- Added support for background jobs
```cpp
auto loader = RED4ext::ResourceLoader::Get();
auto token = loader->LoadAsync(R"(base\vehicles\sport\v_sport1_herrera_outlaw_basic_01.ent)");
{
RED4ext::JobQueue queue; // Jobs in one queue are sequential
queue.Dispatch([]{ Log("Job A-1"); });
queue.Dispatch([]{ Log("Job A-2"); });
queue.Dispatch([]{ Log("Job A-3"); });
Log("Checkpoint A");
}
{ …
```

Background jobs and callbacks

---

include/RED4ext/Memory/SharedPtr.hpp
include/RED4ext/SortedArray.hpp
include/RED4ext/TweakDB-inl.hpp
include/RED4ext/TweakDB.hpp

The main reason for this optimization is editing TweakDB. Flats are stored in a sorted unique array with over 2M entries. Flat insertion is expensive and adds up quickly when creating/cloning records with many properties. 
The new method allows batch insertions. The bigger the batch, the bigger the gain.
| N of insertions | Avg. boost |
|---|---|
| 10 | 8x |
| 100 | 25x |
| 1000 | 170x |
With this optimization applied to creating/cloning records, a real mod that adds items shows around 20x faster load times (each item record has 80-110 properties).

Optimized sorted array merging 

---

.clang-format
include/RED4ext/Addresses.hpp
include/RED4ext/Callback.hpp
include/RED4ext/RTTITypes.hpp
include/RED4ext/ResourceLoader.hpp
include/RED4ext/ResourceReference.hpp
include/RED4ext/Scripting/CProperty.hpp
scripts/patterns.py

- Updated `CRTTIBaseArrayType` vft
- Fixed `FlexCallback` ctor to properly initialize allocator ptr
- Removed `ResourceToken::Unk38` as it can cause issues until fully decoded
- Removed unneeded `const` from `ResourceToken`
- Added assignment operators for `ResourceAsyncReference`
- Made `CProperty::GetValuePtr()` public

Various fixes

---

include/RED4ext/Addresses.hpp
include/RED4ext/CString-inl.hpp
include/RED4ext/CString.hpp
include/RED4ext/Dump/Reflection-inl.hpp
include/RED4ext/Handle.hpp
include/RED4ext/Scripting/Natives/CResource.hpp
include/RED4ext/Scripting/Natives/Generated/ink/WidgetLibraryResourceWrapper.hpp
include/RED4ext/Scripting/Natives/gameAppearanceNameVisualTagsPreset.hpp
include/RED4ext/Scripting/Natives/gamePersistentState.hpp
include/RED4ext/Scripting/Natives/gamedataTweakDBRecord.hpp
include/RED4ext/Scripting/Natives/inkChildren.hpp
include/RED4ext/Scripting/Natives/inkIWidgetLogicController.hpp
include/RED4ext/Scripting/Natives/inkLayer.hpp
include/RED4ext/Scripting/Natives/inkLayerProxy.hpp
include/RED4ext/Scripting/Natives/inkMultiChildren.hpp
include/RED4ext/Scripting/Natives/inkWidget.hpp
include/RED4ext/TweakDB.hpp
scripts/patterns.py

- Added `CSstring` ctors and operators
- Fixed conflicts for scripted aliases (sometimes they use the same name as another existing native type)
- Fixed conflict for `TweakDBRecord` and generated type
- Removed `SelfHandle`

Small fixes

---

include/RED4ext/Api/Sdk.hpp
include/RED4ext/Api/v0/Scripts.hpp
include/RED4ext/Api/v0/Sdk.hpp

Paired with https://github.com/WopsS/RED4ext/pull/21
> Paths can be added via the Scripts::Add function in the sdk, during Load:
>
>     aSdk->scripts->Add(aHandle, L"module.reds");
>
> Paths can either directories or files (handled by scc), relative to the plugin's folder, or absolute (mainly for testing/development).
>
> This will also force script compilation when REDmods are enabled, which will cause double-compilation if cybercmd is installed - cybercmd is no longer needed for this scenario.

Adds Scripts to SDK for loading redscript through RED4ext

---

include/RED4ext/Callback.hpp
include/RED4ext/ResourceReference.hpp

- Fixed flexible callbacks
- Added comparison operators for `ResourceAsyncReference`

Fixed callbacks

---

include/RED4ext/HashMap.hpp
include/RED4ext/Scripting/Natives/Generated/game/IAttachmentSlotsListener.hpp
include/RED4ext/Scripting/Natives/gameIAttachmentSlotsListener-inl.hpp
include/RED4ext/Scripting/Natives/gameIAttachmentSlotsListener.hpp
include/RED4ext/Scripting/Natives/gameITransactionSystem.hpp
src/Scripting/Natives/gameIAttachmentSlotsListener.cpp

Found that HashMap deletions are broken.
I was lucky to find an implementation in TransactionSystem and adjusted ours accourdigly.
Sombra's implementation was pretty accurate except one tiny mistake:
```cpp
while (idx != INVALID_INDEX)
{
Node* prevNode = nullptr; // should've been outside of loop :)
Node* node = &nodes[idx];
...
prevNode = node;
idx = node->next;
}
```
For reference their implementation can be found here:
`83 7D ? ? 74 ? 33 D2 8B C3 F7 75 ? 48 8B 45 ? 8B 0C 90 48 8D 14 90 83 F9 ? 74 ? 44 8B 45 ? 4C 8B 4D`

Fixed HashMap + more TransactionSystem

---

include/RED4ext/TLS-inl.hpp

When trying to compile CyberEngineTweaks with the latest patch-2.0 branch, the compilation fails with
```
error: TLS.cpp
vendor\RED4ext.SDK\include\RED4ext/TLS-inl.hpp(9): error C3861: '__readgsqword': identifier not found
```
Including `intrin.h` solves that.

Fix compilation of TLS-inl.hpp

---

include/RED4ext/Addresses.hpp
include/RED4ext/Scripting/ScriptReport-inl.hpp
include/RED4ext/Scripting/ScriptReport.hpp
src/Scripting/ScriptReport.cpp

Moved over from https://github.com/psiberx/cp2077-red-hot-tools

feat: add requirements for script validation

---

include/RED4ext/NativeTypes-inl.hpp

I forgot to remove constness in implementation of CurveData<T> in previous commit.
Currently, compilation will fail when trying to use CurveData.

Fix implementation of CurveData<T> with RawBuffer.

---

include/RED4ext/DynArray.hpp

- Fixed `Reserve()` which reallocated the buffer even there was enough capacity
- Added proper buffer deinitialization in dtor

Fixed DynArray

---

include/RED4ext/JobQueue-inl.hpp
include/RED4ext/Memory/Utils.hpp

fixes an issue with the code relying on msvc specific behavior in 2 places
- one [[nodiscard]] attribute
- I think `GetAllocator` relies on a bug in two-phase lookup in MSVC: https://blog.llvm.org/2009/12/dreaded-two-phase-name-lookup.html

fix: fix clang compat

---

include/RED4ext/Buffer.hpp
include/RED4ext/GameEngine.hpp
include/RED4ext/Memory/Pool.hpp
include/RED4ext/Mutex-inl.hpp
include/RED4ext/Mutex.hpp
include/RED4ext/RED4ext.hpp
include/RED4ext/RTTISystem.hpp
include/RED4ext/RTTITypes.hpp
include/RED4ext/ResourceLoader.hpp
include/RED4ext/Scripting/Natives/inkHUDLayer.hpp
include/RED4ext/Scripting/Natives/inkMultiChildren.hpp
include/RED4ext/Scripting/Natives/inkWidget.hpp
include/RED4ext/Scripting/Natives/inkWorldLayer.hpp
include/RED4ext/SharedMutex.hpp
include/RED4ext/SharedSpinLock-inl.hpp
include/RED4ext/SharedSpinLock.hpp
include/RED4ext/TweakDB-inl.hpp
include/RED4ext/TweakDB.hpp
src/Mutex.cpp
src/SharedSpinLock.cpp

I was looking into the RTTI and there appear to be 4 types of locks:
- spin lock (currently named SpinLock in the SDK)
- shared spin lock (currently named SharedMutex in the SDK)
- mutex (uses critical section, does not exist in the SDK)
- shared mutex (uses srwlock, does not exist in the SDK)
In this PR I do a little bit of cleanup:
- rename `SharedMutex` to `SharedSpinLock`, because that's the more appopriate name, in c++ a shared mutex corresponds to a srwlock on Windows, not a spin lock
- introduce `Mutex`
- update the RTTI system to make use of `Mutex` and `SharedSpinLock`
I didn't add the rwlock because I don't think it's needed anywhere in the SDK right now.

Rename SharedMutex and introduce Mutex

---

include/RED4ext/Buffer-inl.hpp
include/RED4ext/Buffer.hpp
include/RED4ext/CName.hpp
include/RED4ext/NativeTypes.hpp
include/RED4ext/ResourcePath.hpp

- Added raw buffer resize method
- Added alternative ctors for `CName`, `TweakDBID`, `ResourcePath`, that accept non-null-terminated strings

Various changes

---

include/RED4ext/Scripting/Natives/Generated/vehicle/BaseObject.hpp
include/RED4ext/Scripting/Natives/vehicleBaseObject.hpp

Property offset at 0x25C, useful for readonly usage.
Thanks to [Jack for RE](https://github.com/jackhumbert/let_there_be_flight/blob/4117943a72afe3c6add8711da93226020ff0dc3f/src/redscript/Extensions/VehicleObject.reds#L42).
Property tested on 2.12a with success.

Add vehicleBaseObject::isOnGround and generate stub.

---

include/RED4ext/NativeTypes-inl.hpp
include/RED4ext/NativeTypes.hpp

Allows user to resize the number of points in a CurveData. Data is kept as-is, shrinking will only lose last points, growing will only add random/empty points.
FYI, I haven't tested it myself.

Add CurveData::Resize

---

CMakeLists.txt
examples/CMakeLists.txt
include/RED4ext/Relocation-inl.hpp
include/RED4ext/Relocation.hpp

This should improve the error message thrown by `UniversalRelocBase` class when an hash is not found. It now include more informational messages for the users, as well as the mod's name in the title, instead of the generic `RED4ext.SDK`, except in the case where we cannot get the plugin's handle, which should never happen.
Some examples:

Improve error reporting for UniversalReloc class

---

include/RED4ext/HashMap.hpp

Fixed hash function for `uint64_t`. Also checked hashing for `CName`, `TweakDBID`, `ResourcePath` and all of them are still correct at the moment.

Fixed HashMap for uint64 keys

---

include/RED4ext/Memory/Allocators.hpp

- missing template keyword calling dependent function name
- missing default initialization for AllocationResult
- disable ReSharper virtual destructor check
- reformat
- remove deprecated structs

Fix Allocator issues reported by ReSharper

---

include/RED4ext/GpuApi/Buffer.hpp
include/RED4ext/GpuApi/CommandListContext-inl.hpp
include/RED4ext/GpuApi/CommandListContext.hpp
include/RED4ext/GpuApi/D3D12MemAlloc.hpp
include/RED4ext/GpuApi/DeviceData-inl.hpp
include/RED4ext/GpuApi/DeviceData.hpp
include/RED4ext/GpuApi/SwapChain.hpp
src/GpuApi/DeviceData.cpp

- fix mistakes from #164
- SDeviceData may in the end be null directly after hooking, looked at the wrong code point during review
- CString* instead of const char* for GetFreeCommandList
- multiple missing pragma once
- case in header files and their ordering
- pulled things that should have been pulled into corresponding -inl.hpp and made .cpp files when necessary
- extend ResourceContainer and ResourceContainer::Resource with additional data and helpers
- add SSwapChainData and corresponding ResourceContainer into SDeviceDataBase
- add proper SpinLock reference for ResourceContainers and SDeviceDataBase

Add SSwapChainData and fix mistakes in former PR

---

include/RED4ext/Detail/AddressHashes.hpp
include/RED4ext/GpuApi/CommandListContext-inl.hpp
include/RED4ext/GpuApi/CommandListContext.hpp
include/RED4ext/GpuApi/DeviceData.hpp
include/RED4ext/ISerializable.hpp
include/RED4ext/Memory/UniquePtr.hpp
include/RED4ext/RED4ext.hpp

- Added `UniquePtr` implementation.
- Added `CommandListContext` destructor.
- Wrapped `CommandListContext` in `UniquePtr`.

Added UniquePtr implementation

---

include/RED4ext/GameEngine-inl.hpp
include/RED4ext/GameEngine.hpp

Tested locally with simple parameters for `rend::SingleScreenShotData`. Boolean argument is unknown. Trying with both `false`/`true` didn't changed the output in my test. Using `false` as a default anyway.
Many thanks to @Mozz3d for reverse engineering the method 👍 
Edit: hash of the function `3668449892`.

feat(CGameEngine): add TakeScreenshot method

---

include/RED4ext/RenderProxy.hpp

`IRenderProxy` was missing allocator type required for `SharedPtr<IRenderProxy>`.

Fixed render proxy
