include/RED4ext/DynArray.hpp, include/RED4ext/HashMap.hpp, include/RED4ext/Map.hpp, include/RED4ext/REDhash.hpp, include/RED4ext/SortedArray.hpp, include/RED4ext/Types/SharedMutex.hpp, include/RED4ext/Types/SimpleTypes-inl.hpp, include/RED4ext/Types/SimpleTypes.hpp, include/RED4ext/Types/TweakDB-inl.hpp, include/RED4ext/Types/TweakDB.hpp
=> SortedArray/Map and TweakDB again

include/RED4ext/Types/TweakDB-inl.hpp
removed 'static' from 'fakeTweakDB'. was useless anyway
=> fix multithread issue with TweakDB::UpdateRecord

include/RED4ext/CName-inl.hpp, include/RED4ext/CName.hpp, include/RED4ext/DynArray.hpp, include/RED4ext/GameEngine.hpp, include/RED4ext/SortedArray.hpp
constexpr CName
fixing arrays ctor
GameInstance::unk40 -> HashMap<IRTTIType*, IRTTIType*> unk48
=> constexpr CName and fixes

include/RED4ext/Types/TweakDB-inl.hpp
fix for https://discord.com/channels/717692382849663036/795037494106128434/871885536695046144
=> fix TweakDB default values

include/RED4ext/Scripting/Functions.hpp
Tiny update for function flags.
=> Update flags for CBaseFunction

examples/native_class_redscript/Main.cpp, examples/native_class_redscript/MyCustomClass.reds, examples/native_class_redscript/premake5.lua
Redscript file also includes a script system that runs on load for testing.
=> Adds Native Class Example with Redscript

include/RED4ext/NativeTypes-inl.hpp, include/RED4ext/NativeTypes.hpp
Full Variant support. I'll add some usage examples later.
=> Improve Variant support

include/RED4ext/Common.hpp, include/RED4ext/Hashing/FNV1a.hpp, include/RED4ext/Map.hpp, include/RED4ext/RTTITypes.hpp, include/RED4ext/Scripting/Stack.hpp
- made the code clang-compatible
- added a small `Step` function
=> Small changes for the bindings

include/RED4ext/Addresses.hpp, include/RED4ext/NativeTypes-inl.hpp, include/RED4ext/NativeTypes.hpp, include/RED4ext/RTTISystem.hpp, include/RED4ext/RTTITypes.hpp, include/RED4ext/ResourcePath.hpp, include/RED4ext/ResourceReference-inl.hpp, include/RED4ext/ResourceReference.hpp, include/RED4ext/Scripting/Stack-inl.hpp, include/RED4ext/Scripting/Stack.hpp, include/RED4ext/Scripting/Utils-inl.hpp, include/RED4ext/Scripting/Utils.hpp, scripts/patterns.py, src/ResourceReference.cpp
- Add `ResourcePath` with sanitations
- Decode more `ResourceReference` and `ResourceAsyncReference`
- Decode more `CStackFrame`
- Update `GetParameter` helper so it can be used for "out" params (gives direct ptr to the scripted value so that it can be modified from native function)
- Decode some `IRTTISystem` members
- Fix `CEnum` members
=> Scripting and resource improvements

.github/workflows/build.yml, CMakeLists.txt, cmake/pch.hpp.in
By using precompiled headers the build time is reduced by approximately 1 minute on my machine.
=> Add option to be able to generate precompiled headers

include/RED4ext/Detail/Memory.hpp, include/RED4ext/JobQueue-inl.hpp, include/RED4ext/SortedArray.hpp
- Added missing `RED4EXT_INLINE` specifiers
- Fixed return value of `SortedArray::Merge()`
- Adjusted memory concepts to be more accurate (and for better clang compatibility)
=> Small fixes

include/RED4ext/DynArray.hpp, include/RED4ext/HashMap.hpp, include/RED4ext/Scripting/Natives/Generated/ink/ControllerProcessor.hpp, include/RED4ext/Scripting/Natives/Generated/ink/Layer.hpp, include/RED4ext/Scripting/Natives/Generated/ink/VirtualWindow.hpp, include/RED4ext/Scripting/Natives/Generated/red/ResourceReferenceScriptToken.hpp, include/RED4ext/Scripting/Natives/inkControllerProcessor.hpp, include/RED4ext/Scripting/Natives/inkLayer.hpp, include/RED4ext/SortedArray.hpp, include/RED4ext/TweakDB-inl.hpp
- Fixed memory leaks in containers
- Fixed flat value creation in TweakDB (the value should've been moved to the buffer, not copied)
- Decoded more widget classes
=> Fixed containers and more decoded classes

include/RED4ext/DynArray.hpp, include/RED4ext/NativeTypes-inl.hpp, include/RED4ext/NativeTypes.hpp, include/RED4ext/Scripting/Natives/Generated/ink/CharacterEvent.hpp, include/RED4ext/Scripting/Natives/Generated/red/TagList.hpp, include/RED4ext/Scripting/Natives/entEntityID.hpp, include/RED4ext/Scripting/Natives/gameIEntitySpawnerEventsBroadcaster.hpp, include/RED4ext/Scripting/Natives/gameIPopulationSystem.hpp, include/RED4ext/Scripting/Natives/gamePersistentID.hpp, include/RED4ext/Scripting/Natives/inkCharacterEvent.hpp, include/RED4ext/Scripting/Natives/redTagList-inl.hpp, include/RED4ext/Scripting/Natives/redTagList.hpp, src/Scripting/Natives/redTagList.cpp
- Various small fixes
- Decoded `inkCharacterEvent`
- Added constexpr `TweakDBID` (static and header-only)
- Added `TagList` methods
=> Small fixes + inkCharacterEvent

include/RED4ext/Callback.hpp, include/RED4ext/Detail/AddressHashes.hpp, include/RED4ext/Detail/Callback.hpp, include/RED4ext/Detail/Function.hpp, include/RED4ext/NativeTypes-inl.hpp, include/RED4ext/NativeTypes.hpp, include/RED4ext/Scripting/Natives/Generated/ink/HUDLayer.hpp, include/RED4ext/Scripting/Natives/Generated/ink/HudWidgetSpawnEntry.hpp, include/RED4ext/Scripting/Natives/Generated/ink/IWidgetComponentWrapper.hpp, include/RED4ext/Scripting/Natives/Generated/ink/WorldLayer.hpp, include/RED4ext/Scripting/Natives/inkHUDLayer.hpp, include/RED4ext/Scripting/Natives/inkHudWidgetSpawnEntry.hpp, include/RED4ext/Scripting/Natives/inkIWidgetComponentWrapper.hpp, include/RED4ext/Scripting/Natives/inkLayer.hpp, include/RED4ext/Scripting/Natives/inkWorldLayer.hpp
- Decoded `DeferredDataBuffer`
```cpp
auto bufferToken = buffer.LoadAsync();
bufferToken->OnLoaded([](auto& buffer) {
auto dataPtr = buffer.raw->data;
});
```
- Decoded more widget classes
- Fixed red callbacks
=> Decoded DeferredDataBuffer and widget classes

include/RED4ext/Detail/AddressHashes.hpp, include/RED4ext/ISerializable-inl.hpp, include/RED4ext/ISerializable.hpp, include/RED4ext/Package-inl.hpp, include/RED4ext/Package.hpp, include/RED4ext/Range.hpp, include/RED4ext/Scripting/Natives/Generated/appearance/AppearanceDefinition.hpp, include/RED4ext/Scripting/Natives/Generated/ent/Entity.hpp, include/RED4ext/Scripting/Natives/Generated/ent/EntityTemplate.hpp, include/RED4ext/Scripting/Natives/Generated/ent/IComponent.hpp, include/RED4ext/Scripting/Natives/appearanceAppearanceDefinition.hpp, include/RED4ext/Scripting/Natives/entEntity.hpp, include/RED4ext/Scripting/Natives/entEntityTemplate.hpp, include/RED4ext/Scripting/Natives/entIComponent.hpp, src/Package.cpp
- Added object package reader and extractor to get objects from buffers
- Decoded more entity related types
=> Added object package reading

include/RED4ext/Detail/Memory.hpp, include/RED4ext/DynArray.hpp, include/RED4ext/Relocation-inl.hpp, include/RED4ext/Scripting/Natives/Generated/anim/Rig.hpp, include/RED4ext/Scripting/Natives/animRig.hpp
- Added address resolver override so CET can keep using original SDK
- Fixed path to `animRig` override
=> Allow address resolver override

include/RED4ext/DynArray.hpp
Fixes my previous fix #127, sorry :)
=> Fixed DynArray

include/RED4ext/Scripting/Natives/Generated/anim/AnimVariableBool.hpp, include/RED4ext/Scripting/Natives/Generated/anim/AnimVariableFloat.hpp, include/RED4ext/Scripting/Natives/Generated/anim/AnimVariableInt.hpp, include/RED4ext/Scripting/Natives/Generated/anim/AnimVariableQuaternion.hpp, include/RED4ext/Scripting/Natives/Generated/anim/AnimVariableTransform.hpp, include/RED4ext/Scripting/Natives/Generated/anim/AnimVariableVector.hpp, include/RED4ext/Scripting/Natives/Generated/anim/Rig.hpp, include/RED4ext/Scripting/Natives/Generated/ent/EntityTemplate.hpp, include/RED4ext/Scripting/Natives/Generated/ink/DrawArea.hpp, include/RED4ext/Scripting/Natives/Generated/quest/ICharacterConditionType.hpp, include/RED4ext/Scripting/Natives/entIPlacedComponent.hpp
Fix format with generated clang-format (style commit).
Add RE property and generate stub (feat commit).
Let me know if something is off.
=> Add IPlacedComponent::worldTransform

include/RED4ext/Scripting/Natives/WorldPosition.hpp
Vector4 is not included while used in constructor of WorldPosition.
=> fix: compilation error when including WorldPosition

CONTRIBUTING.md
Fix typos.
Provide insights and tips on how generated classes can be extended with reverse engineered members.
Let me know if there are mistakes / steps I missed / ...
=> Add steps to declare new fields in CONTRIBUTING.md

include/RED4ext/Scripting/Natives/vehicleBaseObject.hpp
All properties tested on `2.12a`.
=> feat: add more properties on vehicleBaseObject.

include/RED4ext/Scripting/Natives/Generated/game/GameSessionDesc.hpp, include/RED4ext/Scripting/Natives/Generated/world/WorldID.hpp, include/RED4ext/Scripting/Natives/gameGameSessionDesc.hpp, include/RED4ext/Scripting/Natives/worldWorldID.hpp
I'm a bit unsure about some things, but I think it's fine
=> Decoded game::GameSessionDesc and world::WorldID

include/RED4ext/Scripting/Natives/gameGameSessionDesc.hpp
These seem to need to be set for the session desc to actually load into a game
=> Updated game::GameSessionDesc with ctor + more decoding

include/RED4ext/Buffer-inl.hpp, include/RED4ext/Buffer.hpp, include/RED4ext/Detail/AddressHashes.hpp, include/RED4ext/NativeTypes-inl.hpp, include/RED4ext/ResourceLoader-inl.hpp, include/RED4ext/ResourceLoader.hpp, include/RED4ext/Scripting/Natives/EngineTime.hpp, include/RED4ext/Scripting/Natives/Generated/EngineTime.hpp
- Added method to load resource with additional loader params
- Added method to get raw buffer allocator
- Added check that buffer is initialized when getting the size of `CurveData`
- Added `EngineTime::ticks` property
=> Updated ResourceLoader, RawBuffer, CurveData

include/RED4ext/Scripting/Natives/Generated/move/Component.hpp, include/RED4ext/Scripting/Natives/moveComponent.hpp
- generate stub
- add properties found with RedMemoryDump
=> feat: add move/position properties in move::Component

include/RED4ext/TweakDB-inl.hpp
Fixed typo in TweakDB flat allocation.
=> Fix TweakDB flat allocation
